preset: "conventionalcommits"
release-rules:
  - type: "feat"
    release: "minor"
  - type: "fix"
    release: "patch"
  - type: "perf"
    release: "patch"
  - type: "refactor"
    release: "patch"
  - type: "chore"
    release: false
  - type: "docs"
    release: false
  - type: "style"
    release: false
  - type: "test"
    release: false
  - type: "ci"
    release: false
  - type: "build"
    release: false
  - breaking: true
    release: "major"

pre-release-branches:
  - "develop"
  - "beta"
  - "alpha"

changelog:
  disable: false
  docker:
    registry: ""
  hooks:
    before:
      - "echo 'Generating changelog...'"
    after:
      - "echo 'Changelog generated successfully'"